### ISSUE TITLE
Data is not copying on initial sync  into clickhouse (copies only tables with structure but no data is populated)

### ISSUE THREAD

**Issue by simplecrm-github** [bakwc/mysql_ch_replicator#16]
Hi, I tried to do the initial sync with the below cmd but unfortunately, the data is not copying into clickhouse database from mysql and I am using the 0.0.26 version for mysql_ch_replicator.

 mysql_ch_replicator --config settings.yaml db_replicator --db testdb --target_db testdb --initial_only=True
[dbrepl testdb 2024-11-08 01:29:12,157     INFO] launched db_replicator
[dbrepl testdb 2024-11-08 01:29:12,157     INFO] recreating database
[dbrepl testdb 2024-11-08 01:29:12,169     INFO] last known transaction None
[dbrepl testdb 2024-11-08 01:29:12,205     INFO] running initial replication
[dbrepl testdb 2024-11-08 01:29:12,205     INFO] running initial replication for table acl_actions
[dbrepl testdb 2024-11-08 01:29:12,206     INFO] replicating from scratch
[dbrepl testdb 2024-11-08 01:29:12,207     INFO] initial replication - swapping database
[dbrepl testdb 2024-11-08 01:29:12,219     INFO] initial replication - done
[dbrepl testdb 2024-11-08 01:29:12,220     INFO] skip running realtime replication, only initial replication was requested

could you please help with this?

my config settings:

vi settings.yaml
mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'xxxxxx'

clickhouse:
  host: 'localhost'
  port: 8123
  user: 'default'
  password: 'default'

binlog_replicator:
  data_dir: '/binlog/'
  records_per_file: 100000

databases: 'testdb'
tables: '*'

**Comment by bakwc** [comment]
1) How many tables does your `testdb` has?
2) From logs I see there is only one table called `acl_actions`. Could you please share the structure of this table? (show create table acl_actions)

**Comment by bakwc** [comment]
I added more detailed logs in a new version. Could you please:
 1. Update to `0.0.29`
 2. Set `log_level: 'debug'` in `config.yaml` (see README.md for example)

**Comment by simplecrm-github** [comment]
1. updated to 0.0.29
2. Enabled log_level to debug and ran the initial sync cmd and please find the details as below.

mysql_ch_replicator --config settings.yaml db_replicator --db testdb --initial_only=True
[dbrepl testdb 2024-11-11 14:09:29,275     INFO] launched db_replicator
[dbrepl testdb 2024-11-11 14:09:29,275     INFO] recreating database
[dbrepl testdb 2024-11-11 14:09:29,300     INFO] last known transaction None
[dbrepl testdb 2024-11-11 14:09:29,338     INFO] running initial replication
[dbrepl testdb 2024-11-11 14:09:29,338     INFO] running initial replication for table acl_actions
[dbrepl testdb 2024-11-11 14:09:29,339     INFO] replicating from scratch
[dbrepl testdb 2024-11-11 14:09:29,339    DEBUG] mysql table structure: TableStructure(fields=[TableField(name='id', field_type='char(36)', parameters='NOT NULL'), TableField(name='date_entered', field_type='datetime', parameters='DEFAULT NULL'), TableField(name='date_modified', field_type='datetime', parameters='DEFAULT NULL'), TableField(name='modified_user_id', field_type='char(36)', parameters='DEFAULT NULL'), TableField(name='created_by', field_type='char(36)', parameters='DEFAULT NULL'), TableField(name='name', field_type='varchar(150)', parameters='DEFAULT NULL'), TableField(name='category', field_type='varchar(100)', parameters='DEFAULT NULL'), TableField(name='acltype', field_type='varchar(100)', parameters='DEFAULT NULL'), TableField(name='aclaccess', field_type='int', parameters='DEFAULT NULL'), TableField(name='deleted', field_type='tinyint(1)', parameters='DEFAULT NULL')], primary_key='id', primary_key_idx=0, table_name='acl_actions')
[dbrepl testdb 2024-11-11 14:09:29,339    DEBUG] clickhouse table structure: TableStructure(fields=[TableField(name='id', field_type='String', parameters=''), TableField(name='date_entered', field_type='Nullable(DateTime64)', parameters=''), TableField(name='date_modified', field_type='Nullable(DateTime64)', parameters=''), TableField(name='modified_user_id', field_type='Nullable(String)', parameters=''), TableField(name='created_by', field_type='Nullable(String)', parameters=''), TableField(name='name', field_type='Nullable(String)', parameters=''), TableField(name='category', field_type='Nullable(String)', parameters=''), TableField(name='acltype', field_type='Nullable(String)', parameters=''), TableField(name='aclaccess', field_type='Nullable(Int32)', parameters=''), TableField(name='deleted', field_type='Nullable(Bool)', parameters='')], primary_key='id', primary_key_idx=0, table_name='acl_actions')
[dbrepl testdb 2024-11-11 14:09:29,339    DEBUG] primary key name: id, type: String
[dbrepl testdb 2024-11-11 14:09:29,340    DEBUG] extracted 0 records from mysql
[dbrepl testdb 2024-11-11 14:09:29,341    DEBUG] records: []
[dbrepl testdb 2024-11-11 14:09:29,341     INFO] finish replicating acl_actions, replicated 0 records, primary key: None
[dbrepl testdb 2024-11-11 14:09:29,341     INFO] initial replication - swapping database
[dbrepl testdb 2024-11-11 14:09:29,355     INFO] initial replication - done
[dbrepl testdb 2024-11-11 14:09:29,355     INFO] skip running realtime replication, only initial replication was requested

>>
It shows 0 records in the clickhouse db.

**Comment by simplecrm-github** [comment]
it has only one table - acl_actions 

1. MySQL table - structure.

CREATE TABLE `acl_actions` (
  `id` char(36) NOT NULL,
  `date_entered` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `modified_user_id` char(36) DEFAULT NULL,
  `created_by` char(36) DEFAULT NULL,
  `name` varchar(150) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `acltype` varchar(100) DEFAULT NULL,
  `aclaccess` int DEFAULT NULL,
  `deleted` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


2.  Clickhose table - structure (created when running the sync from MySQL using replicator cmd)


   ┌─statement──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
1. │ CREATE TABLE testdb.acl_actions
(
    `id` String,
    `date_entered` Nullable(DateTime64(3)),
    `date_modified` Nullable(DateTime64(3)),
    `modified_user_id` Nullable(String),
    `created_by` Nullable(String),
    `name` Nullable(String),
    `category` Nullable(String),
    `acltype` Nullable(String),
    `aclaccess` Nullable(Int32),
    `deleted` Nullable(Bool),
    `_version` UInt64,
    INDEX _version _version TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY id
SETTINGS index_granularity = 8192 │

**Comment by bakwc** [comment]
Thanks for providing logs.
I see that primary key has `char` / `String` type. Usually we have `numeric` primary key type, so probably there is a bug here. I will try to fix it and let you know when ready.

**Comment by bakwc** [comment]
Fixed in `0.0.30`, please update and try again.

**Comment by bakwc** [comment]
Please double check you set the option `<final>1</final>` in clickhouse settings:

```
<clickhouse>
    <!-- ... other settings ... -->
    <profiles>
        <default>
            <!-- ... other settings ... -->
            <final>1</final>
        </default>
    </profiles>
</clickhouse>
```

**Comment by simplecrm-github** [comment]
Hi,

We already set <final>1</final> in config.

How much time does it take to remove duplicate records in clickhouse db when we update a record in MySQL db ?  I've observed that it takes around 15 to 20 minutes to remove duplicates from the clickhouse db.

Below is an example where I updated the name column to 'test' based on the ticket number, but the ClickHouse database is still showing both old and new data.

MySQL:

mysql> select name  from cases where case_number='251892795';
+----------+
| name     |
+----------+
| test1234 |
+----------+
1 row in set (0.00 sec)


Clickhouse:

select name  from cases where case_number='251892795';

SELECT name
FROM cases
WHERE case_number = '251892795'

Query id: a14fa590-c3d0-4539-a3fb-9c556df045bb

   ┌─name─┐
1. │ test │
   └──────┘
   ┌─name─┐
2. │ test1234 │
   └──────┘

  ┌─name─┐
3. │ test1234 │
   └──────┘

How can we make this update real-time, or at least reduce the update record time to 1–2 seconds? Please suggest some solutions.

**Comment by bakwc** [comment]
The `<final>` option is expected to make it work in realtime.
Could you also please:
1) Run`SET final = 1;` before making select query and try again
2) Select all fields (not only name, but other fields too) and attach it here. (There should be `version` field included)
3) Attach table structure in clickhouse and in mysql (`SHOW CREATE TABLE tbl_name`)

**Comment by simplecrm-github** [comment]
1.  Yes  <final> option is already set.
2.  all fields including version.
Row 1:
──────
id:                    8d7d3d3f-a326-11ef-8833-02b84f5ddb23
name:                  test1234
date_entered:          2023-02-13 04:53:18.000
date_modified:         2023-02-13 04:53:18.000
modified_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
created_by:            1de404b9-ff08-4e9a-c3bf-60d485279606
description:
deleted:               false
assigned_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
case_number:           251892795
type:
status:                Open_New
priority:              P1
resolution:            ᴺᵁᴸᴸ
work_log:              ᴺᵁᴸᴸ
account_id:            ᴺᵁᴸᴸ
state:                 Open
contact_created_by_id: ᴺᵁᴸᴸ
_version:              8652159

Row 2:
──────
id:                    8d7d3d3f-a326-11ef-8833-02b84f5ddb23
name:                  test1234
date_entered:          2023-02-13 04:53:18.000
date_modified:         2023-02-13 04:53:18.000
modified_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
created_by:            1de404b9-ff08-4e9a-c3bf-60d485279606
description:
deleted:               false
assigned_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
case_number:           251892795
type:
status:                Open_New
priority:              P1
resolution:            ᴺᵁᴸᴸ
work_log:              ᴺᵁᴸᴸ
account_id:            ᴺᵁᴸᴸ
state:                 Open
contact_created_by_id: ᴺᵁᴸᴸ
_version:              8652155

Row 3:
──────
id:                    8d7d3d3f-a326-11ef-8833-02b84f5ddb23
name:                  test1234567
date_entered:          2023-02-13 04:53:18.000
date_modified:         2023-02-13 04:53:18.000
modified_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
created_by:            1de404b9-ff08-4e9a-c3bf-60d485279606
description:
deleted:               false
assigned_user_id:      1de404b9-ff08-4e9a-c3bf-60d485279606
case_number:           251892795
type:
status:                Open_New
priority:              P1
resolution:            ᴺᵁᴸᴸ
work_log:              ᴺᵁᴸᴸ
account_id:            ᴺᵁᴸᴸ
state:                 Open
contact_created_by_id: ᴺᵁᴸᴸ
_version:              8652157

3. Table structure

**Clickhouse:**

1. │ CREATE TABLE crmtestmysqldb.cases
(
    `id` String,
    `name` Nullable(String),
    `date_entered` Nullable(DateTime64(3)),
    `date_modified` Nullable(DateTime64(3)),
    `modified_user_id` Nullable(String),
    `created_by` Nullable(String),
    `description` Nullable(String),
    `deleted` Nullable(Bool),
    `assigned_user_id` Nullable(String),
    `case_number` Int32,
    `type` Nullable(String),
    `status` Nullable(String),
    `priority` Nullable(String),
    `resolution` Nullable(String),
    `work_log` Nullable(String),
    `account_id` Nullable(String),
    `state` Nullable(String),
    `contact_created_by_id` Nullable(String),
    `_version` UInt64,
    INDEX _version _version TYPE minmax GRANULARITY 1,
    INDEX idx_id id TYPE bloom_filter GRANULARITY 1
)
ENGINE = ReplacingMergeTree(_version)
ORDER BY id
SETTINGS index_granularity = 8192 │


**MySQL** 

CREATE TABLE `cases` (
  `id` char(36) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `date_entered` datetime DEFAULT NULL,
  `date_modified` datetime DEFAULT NULL,
  `modified_user_id` char(36) DEFAULT NULL,
  `created_by` char(36) DEFAULT NULL,
  `description` text,
  `deleted` tinyint(1) DEFAULT '0',
  `assigned_user_id` char(36) DEFAULT NULL,
  `case_number` int NOT NULL AUTO_INCREMENT,
  `type` varchar(255) DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `priority` varchar(100) DEFAULT NULL,
  `resolution` text,
  `work_log` text,
  `account_id` char(36) DEFAULT NULL,
  `state` varchar(100) DEFAULT 'Open',
  `contact_created_by_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `casesnumk` (`case_number`),
  KEY `idx_case_name` (`name`),
  KEY `idx_account_id` (`account_id`),
  KEY `idx_source_c` (`priority`),
  KEY `idx_status` (`status`),
  KEY `idx_assigned_user_id` (`assigned_user_id`),
  KEY `idx_modified_user_id` (`modified_user_id`),
  KEY `idx_date_modified` (`date_modified`),
  KEY `case_number` (`case_number`),
  KEY `idx_date_entered` (`date_entered`),
  KEY `idx_cases_stat_del` (`assigned_user_id`,`status`,`deleted`),
  KEY `idx_status_name_date` (`status`,`name`,`deleted`,`date_entered`),
  KEY `category` (`type`),
  KEY `idx_deleted` (`deleted`),
  KEY `date_type_del` (`date_entered`,`type`,`deleted`),
  KEY `accound_id_del` (`account_id`,`deleted`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_dateentered` (`date_entered`),
  KEY `idx_accid_ass_date_type_del` (`id`,`account_id`,`assigned_user_id`,`date_entered`,`type`,`deleted`),
  KEY `idx_case_type_date` (`type`,`deleted`,`date_entered`),
  KEY `idx_status_del` (`status`,`deleted`),
  KEY `assigned_del_date` (`assigned_user_id`,`deleted`,`date_entered`),
  KEY `assigned_del_name` (`assigned_user_id`,`deleted`,`name`),
  KEY `indx_date_enter_mod_del` (`date_entered`,`date_modified`,`deleted`),
  KEY `contact_created_by_id` (`contact_created_by_id`),
  KEY `account_id` (`account_id`),
  KEY `idx_id_account_modified_date` (`id`,`account_id`,`assigned_user_id`,`modified_user_id`,`date_entered`)
) ENGINE=InnoDB AUTO_INCREMENT=251892796 DEFAULT CHARSET=utf8mb3

**Comment by simplecrm-github** [comment]
<clickhouse>
    
    <profiles>
        <default>
            
            <final>1</final>
        </default>
    </profiles>
</clickhouse>

I have the above settings in /etc/clickhouse-server/config.d/override.xml, is the path correct?

**Comment by simplecrm-github** [comment]
**<clickhouse>
    
    <profiles>
        <default>
            
            <final>1</final>
        </default>
    </profiles>
</clickhouse>**

**Comment by bakwc** [comment]
I will try to reproduce locally and let you know

**Comment by simplecrm-github** [comment]
Ok, sure,

```
<clickhouse>
    <!-- ... other settings ... -->
    <profiles>
        <default>
            <!-- ... other settings ... -->
            <final>1</final>
        </default>
    </profiles>
</clickhouse>
```
I have the above settings in /etc/clickhouse-server/config.d/override.xml, is the path correct?

**Comment by bakwc** [comment]
Could you please run this command in clickhouse and paste output?
`SELECT name, value, changed FROM system.settings WHERE name = 'final'`?

**Comment by simplecrm-github** [comment]
i have set the             <final>1</final>
in /etc/clickhouse-server/users.xml  and now the above query showing as final is enabled

┌─name──┬─value─┬─changed─┐

│ final │ 1 │ 1

 │
└───────┴───────┴─────────┘

**Comment by Deniskore** [comment]
@simplecrm-github, in your case, it might be better to run the following command periodically:

```SQL
OPTIMIZE TABLE table ON CLUSTER your_cluster FINAL;
```

Additionally, you can try reconfiguring your cluster/node to perform this action. More information in [ClickHouse Merge Tree Settings](https://clickhouse.com/docs/en/operations/settings/merge-tree-settings).

**Comment by bakwc** [comment]
> OPTIMIZE TABLE table ON CLUSTER your_cluster FINAL;

This will not work in realtime. For realtime you need to have `final=1` setting enabled.

**Comment by simplecrm-github** [comment]
Yes, now I have enabled final=1, and it seems the update also working without any duplicates.

But I will test it thoroughly and get back to you.

Thanks for the support.

**Comment by simplecrm-github** [comment]
Hi,

So far I have tested deploying click house on a self-hosted VM on AWS EC2.

Is clickhouse cloud compatible with the mysql_ch_replication tool for syncing data from MySQL to clickhouse cloud db as I want to run clickhouse as a managed service?

**Comment by bakwc** [comment]
Yes, it should work, the only question is about ability to set `<final>1</final>` setting. Even if it's not possible, there is a workaround. You may call `SET final = 1;` command directly in SQL in the beginning of your session. (Before executing `SELECT * from TABLE_NAME;` command, execute `SET final = 1;` command)

**Comment by bakwc** [comment]
Closing for now as issue is resolved, feel free to reopen if any other issues / questions.
